### ISSUE TITLE
rsyslog error message on startup

### ISSUE THREAD

**Issue by chrohrer** [sitya/samlidp#4] opened 2019-06-12 13:00 UTC
@sitya I have merged my eduroam and SSHA512 changes into my fork (https://github.com/ubuntunet/samlidp/tree/eduid-africa) of this repository. When I try to start the container, I get the following error message:

```
samli_1  |
samli_1  |  [OK] Nothing to update - your database is already in sync with the current
samli_1  |       entity metadata.
samli_1  |
samli_1  | Main domain (eduid.me) has already been in the database.
samli_1  | rsyslogd: imklog: cannot open kernel log (/proc/kmsg): Operation not permitted.
samli_1  | rsyslogd: activation of module imklog.so failed [v8.40.0 try https://www.rsyslog.com/e/2145 ]
samli_1  | *** WARNING : deprecated key derivation used.
samli_1  | Using -iter or -pbkdf2 would be better.
samli_1  | bad decrypt
samli_1  | 140445984471912:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:crypto/evp/evp_enc.c:570:
```

Any idea what the issue could be?

**Comment by sitya** [comment] 2019-06-12 13:28
Yes, I got exactly the same message in these days, and I did not have time to commit the fix. Actually the rsyslog message is only a warning, the problem is that `des3` became deprecated at in `openssl`, that is why that it cannot decrypt the encrypted key. The fix has been pushed: https://github.com/sitya/samlidp/commit/5ad0b659799d8fcf54923e72769fd5341a2663e3

**Closed by sitya** 2019-06-12 13:28 UTC
